config/routes.rb
Ceremony::Application.routes.draw do

  match 'pages/authenticate' => 'pages#authenticate'
  get "log_in" => "pages#login", :as => "log_in"

  resources :graduations

  resources :enrollments

  resources :students

  resources :faculties

  resources :programs

end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :program
  has_many :enrollments
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  # GET /faculties
  # GET /faculties.xml
  def index
    @faculties = Faculty.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @faculties }
    end
  end

  # GET /faculties/1
  # GET /faculties/1.xml
  def show
    @faculty = Faculty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @faculty }
    end
  end

  # GET /faculties/new
  # GET /faculties/new.xml
  def new
    @faculty = Faculty.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @faculty }
    end
  end

  # GET /faculties/1/edit
  def edit
    @faculty = Faculty.find(params[:id])
  end

  # POST /faculties
  # POST /faculties.xml
  def create
    @faculty = Faculty.new(params[:faculty])

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to(@faculty, :notice => 'Faculty was successfully created.') }
        format.xml  { render :xml => @faculty, :status => :created, :location => @faculty }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @faculty.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /faculties/1
  # PUT /faculties/1.xml
  def update
    @faculty = Faculty.find(params[:id])

    respond_to do |format|
      if @faculty.update_attributes(params[:faculty])
        format.html { redirect_to(@faculty, :notice => 'Faculty was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @faculty.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.xml
  def destroy
    @faculty = Faculty.find(params[:id])
    @faculty.destroy

    respond_to do |format|
      format.html { redirect_to(faculties_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<%= form_for(@faculty) do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :program_id %><br />
    <%= f.text_field :program_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing faculty</h1>

<%= render 'form' %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<h1>Listing faculties</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Available</th>
    <th>Program</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @faculties.each do |faculty| %>
  <tr>
    <td><%= faculty.name %></td>
    <td><%= faculty.available %></td>
    <td><%= faculty.program_id %></td>
    <td><%= link_to 'Show', faculty %></td>
    <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
    <td><%= link_to 'Destroy', faculty, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Faculty', new_faculty_path %>

app/views/faculties/new.html.erb
<h1>New faculty</h1>

<%= render 'form' %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @faculty.name %>
</p>

<p>
  <b>Available:</b>
  <%= @faculty.available %>
</p>

<p>
  <b>Program:</b>
  <%= @faculty.program_id %>
</p>


<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%= link_to 'Back', faculties_path %>