config/routes.rb
Ceremony::Application.routes.draw do

  match 'pages/authenticate' => 'pages#authenticate'
  get "log_in" => "pages#login", :as => "log_in"

  resources :graduations

  resources :enrollments

  resources :students

  resources :faculties

  resources :programs

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :program
  belongs_to :student
  belongs_to :graduation
  belongs_to :faculty
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  # GET /enrollments
  # GET /enrollments.xml
  def index
    @enrollments = Enrollment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @enrollments }
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.xml
  def show
    @enrollment = Enrollment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @enrollment }
    end
  end

  # GET /enrollments/new
  # GET /enrollments/new.xml
  def new
    @enrollment = Enrollment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @enrollment }
    end
  end

  # GET /enrollments/1/edit
  def edit
    @enrollment = Enrollment.find(params[:id])
  end

  # POST /enrollments
  # POST /enrollments.xml
  def create
    @enrollment = Enrollment.new(params[:enrollment])

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to(@enrollment, :notice => 'Enrollment was successfully created.') }
        format.xml  { render :xml => @enrollment, :status => :created, :location => @enrollment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @enrollment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /enrollments/1
  # PUT /enrollments/1.xml
  def update
    @enrollment = Enrollment.find(params[:id])

    respond_to do |format|
      if @enrollment.update_attributes(params[:enrollment])
        format.html { redirect_to(@enrollment, :notice => 'Enrollment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @enrollment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.xml
  def destroy
    @enrollment = Enrollment.find(params[:id])
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to(enrollments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :program_id %><br />
    <%= f.text_field :program_id %>
  </div>
  <div class="field">
    <%= f.label :ceremony_id %><br />
    <%= f.text_field :ceremony_id %>
  </div>
  <div class="field">
    <%= f.label :guest_count %><br />
    <%= f.text_field :guest_count %>
  </div>
  <div class="field">
    <%= f.label :requested_prof %><br />
    <%= f.text_field :requested_prof %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Program</th>
    <th>Ceremony</th>
    <th>Guest count</th>
    <th>Requested prof</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enrollments.each do |enrollment| %>
  <tr>
    <td><%= enrollment.student_id %></td>
    <td><%= enrollment.program_id %></td>
    <td><%= enrollment.ceremony_id %></td>
    <td><%= enrollment.guest_count %></td>
    <td><%= enrollment.requested_prof %></td>
    <td><%= link_to 'Show', enrollment %></td>
    <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
    <td><%= link_to 'Destroy', enrollment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @enrollment.student_id %>
</p>

<p>
  <b>Program:</b>
  <%= @enrollment.program_id %>
</p>

<p>
  <b>Ceremony:</b>
  <%= @enrollment.ceremony_id %>
</p>

<p>
  <b>Guest count:</b>
  <%= @enrollment.guest_count %>
</p>

<p>
  <b>Requested prof:</b>
  <%= @enrollment.requested_prof %>
</p>


<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>